---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/products":
    post:
      summary: Creates a product
      tags:
      - Products
      description: Available only for admin users
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '201':
          description: product created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  external_name:
                    type: string
                  description:
                    type: string
                  manufacturer:
                    type: string
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                  skus:
                    type: array
                    items:
                      type: object
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    external_name:
                      type: string
                    description:
                      type: string
                    manufacturer:
                      type: string
                    active:
                      type: boolean
                  required:
                  - external_name
                  - description
                  - manufacturer
                  - active
    get:
      summary: Retrieves all products paginated
      tags:
      - Products
      responses:
        '200':
          description: products found
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        external_name:
                          type: string
                        description:
                          type: string
                        manufacturer:
                          type: string
                        active:
                          type: boolean
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                        skus:
                          type: array
                          items:
                            type: object
                  pagination:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                        nullable: true
                      current_page:
                        type: integer
                        nullable: true
                      next_page:
                        type: integer
                        nullable: true
                      prev_page:
                        type: integer
                        nullable: true
  "/products/{id}":
    get:
      summary: Retrieves one product
      tags:
      - Products
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Retrieves a product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  external_name:
                    type: string
                  description:
                    type: string
                  manufacturer:
                    type: string
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                  skus:
                    type: array
                    items:
                      type: object
        '404':
          description: product not found
    put:
      summary: Updates a product
      tags:
      - Products
      description: Available only for admin users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '200':
          description: Updates a product
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  external_name:
                    type: string
                  description:
                    type: string
                  manufacturer:
                    type: string
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                  skus:
                    type: array
                    items:
                      type: object
        '404':
          description: Product not found
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product:
                  type: object
                  properties:
                    external_name:
                      type: string
                    description:
                      type: string
                    manufacturer:
                      type: string
                    active:
                      type: boolean
                  required:
                  - external_name
                  - description
                  - manufacturer
                  - active
    delete:
      summary: Delete a product
      tags:
      - Products
      description: Available only for admin users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '204':
          description: Delete a product
        '404':
          description: product not found
        '401':
          description: unauthorized
  "/skus":
    post:
      summary: Creates a sku
      tags:
      - SKUs
      description: Available only for admin users
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '201':
          description: sku created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  external_name:
                    type: string
                  description:
                    type: string
                  manufacturer:
                    type: string
                  active:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
                  skus:
                    type: array
                    items:
                      type: object
        '422':
          description: invalid request
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: object
                  properties:
                    code:
                      type: string
                    names:
                      type: string
                    stock_qty:
                      type: integer
                    table_price_in_cents:
                      type: integer
                    listing_price_in_cents:
                      type: integer
                    product_id:
                      type: integer
                  required:
                  - code
                  - name
                  - stock_qty
                  - table_price_in_cents
                  - listing_price_in_cents
                  - product_id
    get:
      summary: Retrieves all skus paginated
      tags:
      - SKUs
      responses:
        '200':
          description: skus found
          content:
            application/json:
              schema:
                type: object
                properties:
                  skus:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        code:
                          type: string
                        name:
                          type: string
                        stock_qty:
                          type: string
                        table_price_in_cents:
                          type: integer
                        listing_price_in_cents:
                          type: integer
                        product_id:
                          type: integer
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
                  pagination:
                    type: object
                    properties:
                      total_pages:
                        type: integer
                        nullable: true
                      current_page:
                        type: integer
                        nullable: true
                      next_page:
                        type: integer
                        nullable: true
                      prev_page:
                        type: integer
                        nullable: true
  "/skus/{id}":
    get:
      summary: Retrieves one sku
      tags:
      - SKUs
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Retrieves a sku
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  name:
                    type: string
                  stock_qty:
                    type: integer
                  table_price_in_cents:
                    type: integer
                  listing_price_in_cents:
                    type: integer
                  product_id:
                    type: integer
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
        '404':
          description: sku not found
    put:
      summary: Updates a sku
      tags:
      - SKUs
      description: Available only for admin users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '200':
          description: Updates a sku
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  name:
                    type: string
                  stock_qty:
                    type: integer
                  table_price_in_cents:
                    type: integer
                  listing_price_in_cents:
                    type: integer
                  product_id:
                    type: integer
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
        '404':
          description: Product not found
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku:
                  type: object
                  properties:
                    code:
                      type: string
                    names:
                      type: string
                    stock_qty:
                      type: integer
                    table_price_in_cents:
                      type: integer
                    listing_price_in_cents:
                      type: integer
                    product_id:
                      type: integer
                  required:
                  - code
                  - name
                  - stock_qty
                  - table_price_in_cents
                  - listing_price_in_cents
                  - product_id
    delete:
      summary: Delete a sku
      tags:
      - SKUs
      description: Available only for admin users
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: Authorization
        in: header
        schema:
          type: string
        required:
        - Authorization
      responses:
        '204':
          description: Delete a sku
        '404':
          description: sku not found
        '401':
          description: unauthorized
  "/users":
    post:
      summary: Register an user
      tags:
      - User Auth
      parameters: []
      responses:
        '200':
          description: user created
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      password:
                        type: string
                      is_admin:
                        type: boolean
                      token:
                        type: string
        '422':
          description: email already exists
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    is_admin:
                      type: boolean
                  required:
                  - email
                  - password
  "/users/login":
    post:
      summary: User login
      tags:
      - User Auth
      parameters: []
      responses:
        '200':
          description: user logged
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      email:
                        type: string
                      password:
                        type: string
                      is_admin:
                        type: boolean
                      token:
                        type: string
        '422':
          description: email or password invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
